# -*- coding: utf-8 -*-
"""week8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wTAMOPePpsJUVe88m2-YXo4wqlHBOgrQ
"""





import pandas as pd
import numpy as np

# 1. Create a date range for 30 days with 10-minute frequency
start_date = '2023-01-01'
date_range = pd.date_range(start=start_date, periods=30*24*6, freq='10T')
n_rows = len(date_range)

# 2. Generate synthetic data using sine waves and random noise for realism
time_indices = np.arange(n_rows)

# Appliances: base consumption + daily cycle + noise
appliances = 50 + 40 * np.sin(2 * np.pi * time_indices / (24 * 6)) + np.random.randint(0, 50, size=n_rows)

# T3: Indoor temperature around 20C with slight fluctuations
t3 = 20 + 2 * np.sin(2 * np.pi * time_indices / (24 * 6)) + np.random.normal(0, 0.5, n_rows)

# RH_3: Indoor humidity around 40%
rh_3 = 40 + 5 * np.cos(2 * np.pi * time_indices / (24 * 6)) + np.random.normal(0, 1, n_rows)

# T_out: Outdoor temperature with larger daily swings
t_out = 10 + 10 * np.sin(2 * np.pi * time_indices / (24 * 6) - np.pi/2) + np.random.normal(0, 1, n_rows)

# RH_out: Outdoor humidity
rh_out = 70 + 15 * np.cos(2 * np.pi * time_indices / (24 * 6)) + np.random.normal(0, 2, n_rows)

# 3. Combine into DataFrame
df_energy = pd.DataFrame({
    'date': date_range,
    'Appliances': appliances.astype(int),
    'T3': t3,
    'RH_3': rh_3,
    'T_out': t_out,
    'RH_out': rh_out
})

# 4. Save to CSV
csv_filename = 'KAG_energydata_complete.csv'
df_energy.to_csv(csv_filename, index=False)

print(f'Successfully created {csv_filename} with {n_rows} rows.')
df_energy.head()