# -*- coding: utf-8 -*-
"""week7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hu-dv9FccX4p98EpUG8DsIn_L3wYLHiB
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_excel("cleandata.xlsx")
df.head()

df['date'] = pd.to_datetime(df['date'])
df['hour'] = df['date'].dt.hour
df['day'] = df['date'].dt.day
df.head()

cluster_data = df[['Power Consumption','Outdoor Temperature','hour','Occupancy']]
cluster_data.head()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(cluster_data)

from sklearn.cluster import KMeans
inertia = []
for k in range(1,10):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_data)
    inertia.append(kmeans.inertia_)

plt.figure(figsize=(6,4))
plt.plot(range(1,10), inertia, marker='o')

plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("Inertia")

plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)

df['Cluster'] = kmeans.fit_predict(scaled_data)

df.head()

plt.figure(figsize=(6,5))

sns.scatterplot(
    x=df['Outdoor Temperature'],
    y=df['Power Consumption'],
    hue=df['Cluster'],
    palette='viridis'
)

plt.title("Energy Usage Clusters")
plt.show()