# -*- coding: utf-8 -*-
"""week6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11OBroEZ5v0wrTm6XUhgNFVq8hNvt1i9B
"""

import pandas as pd
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

st.title("Sports Facility Night Usage Prediction")

DATA_PATH = "D:\Hack-O-Week\Feb\Week2\LD2011_2014.txt"

@st.cache_data
def load_data():
    df = pd.read_csv(DATA_PATH, sep=";", decimal=",")
    df.rename(columns={df.columns[0]: "timestamp"}, inplace=True)
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df.set_index("timestamp", inplace=True)
    return df

df = load_data()

df = df / 4

hourly = df.resample("H").sum()

meter = hourly.columns[0]
data = hourly[[meter]].copy()
data.columns = ["kwh"]

data["hour"] = data.index.hour
night_data = data[(data["hour"] >= 19) | (data["hour"] <= 2)]

night_data["day_type"] = np.where(night_data.index.dayofweek < 5, "Weekday", "Weekend")
day_filter = st.selectbox("Select Day Type", ["Weekday", "Weekend"])
night_data = night_data[night_data["day_type"] == day_filter]

scaler = MinMaxScaler()
scaled = scaler.fit_transform(night_data[["kwh"]])

def create_seq(data, window=24):
    X, y = [], []
    for i in range(len(data) - window):
        X.append(data[i:i+window])
        y.append(data[i+window])
    return np.array(X), np.array(y)

X, y = create_seq(scaled, 24)

model = Sequential()
model.add(LSTM(32, input_shape=(X.shape[1], 1)))
model.add(Dense(1))
model.compile(optimizer="adam", loss="mse")

model.fit(X, y, epochs=3, batch_size=32, verbose=0)

last_seq = scaled[-24:].reshape(1, 24, 1)
pred = model.predict(last_seq)
pred_kwh = scaler.inverse_transform(pred)[0][0]

st.subheader("Predicted Next Night Electricity Usage")
st.write(round(pred_kwh, 2), "kWh")

recent = night_data["kwh"].tail(50)

plt.figure(figsize=(8,4))
plt.plot(recent.values)
plt.title("Recent Night Usage Trend")
plt.xlabel("Time Step")
plt.ylabel("kWh")
st.pyplot(plt.gcf())

import pandas as pd
import numpy as np

def generate_simulated_data(start_date, end_date, num_meters):
    timestamps = pd.date_range(start=start_date, end=end_date, freq='15min')

    data = {}
    for i in range(1, num_meters + 1):
        data[f'meter_{i}'] = np.random.uniform(0, 100, len(timestamps))

    df = pd.DataFrame(data, index=timestamps)
    df.index.name = "timestamp"

    return df

print("Function 'generate_simulated_data' defined successfully.")

"""**Reasoning**:
The function `generate_simulated_data` has been defined. Now, I will call this function to generate a sample DataFrame with simulated 15-minute electricity usage data for several months, as required by the subtask.


"""

simulated_df = generate_simulated_data(start_date='2023-01-01', end_date='2023-03-31', num_meters=5)
simulated_df.head()

"""## Integrate Sample Data

### Subtask:
Replace the original data loading mechanism with the new function that generates the sample data, and remove Streamlit dependencies to enable local execution.

**Reasoning**:
The subtask requires replacing the original data loading mechanism with the simulated data and removing Streamlit dependencies. I will modify the initial script according to the instructions provided: removing Streamlit imports and related calls, deleting the old data loading logic, and using the `simulated_df` generated earlier.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

df = simulated_df.copy()

df = df / 4

hourly = df.resample("H").sum()

meter = hourly.columns[0]
data = hourly[[meter]].copy()
data.columns = ["kwh"]

data["hour"] = data.index.hour
night_data = data[(data["hour"] >= 19) | (data["hour"] <= 2)].copy()

night_data["day_type"] = np.where(night_data.index.dayofweek < 5, "Weekday", "Weekend")
day_filter = "Weekday"
night_data = night_data[night_data["day_type"] == day_filter]

scaler = MinMaxScaler()
scaled = scaler.fit_transform(night_data[["kwh"]])

def create_seq(data, window=24):
    X, y = [], []
    for i in range(len(data) - window):
        X.append(data[i:i+window])
        y.append(data[i+window])
    return np.array(X), np.array(y)

if len(scaled) >= 24:
    X, y = create_seq(scaled, 24)

    model = Sequential()
    model.add(LSTM(32, input_shape=(X.shape[1], 1)))
    model.add(Dense(1))
    model.compile(optimizer="adam", loss="mse")

    model.fit(X, y, epochs=3, batch_size=32, verbose=0)

    last_seq = scaled[-24:].reshape(1, 24, 1)
    pred = model.predict(last_seq)
    pred_kwh = scaler.inverse_transform(pred)[0][0]

    print(f"Predicted Next Night Electricity Usage: {round(pred_kwh, 2)} kWh")
else:
    print("Not enough data after filtering to create sequences for LSTM model.")
    pred_kwh = None

recent = night_data["kwh"].tail(50)

plt.figure(figsize=(8,4))
plt.plot(recent.values)
plt.title("Recent Night Usage Trend")
plt.xlabel("Time Step")
plt.ylabel("kWh")
plt.show()

"""**Reasoning**:
The previous execution produced a `FutureWarning` regarding the use of 'H' in `df.resample()`. To address this, I will update 'H' to 'h' for hourly resampling, as suggested by the warning.


"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

df = simulated_df.copy()

df = df / 4

hourly = df.resample("h").sum()

meter = hourly.columns[0]
data = hourly[[meter]].copy()
data.columns = ["kwh"]

data["hour"] = data.index.hour
night_data = data[(data["hour"] >= 19) | (data["hour"] <= 2)].copy()

night_data["day_type"] = np.where(night_data.index.dayofweek < 5, "Weekday", "Weekend")
day_filter = "Weekday"
night_data = night_data[night_data["day_type"] == day_filter]

scaler = MinMaxScaler()
scaled = scaler.fit_transform(night_data[["kwh"]])

def create_seq(data, window=24):
    X, y = [], []
    for i in range(len(data) - window):
        X.append(data[i:i+window])
        y.append(data[i+window])
    return np.array(X), np.array(y)

if len(scaled) >= 24:
    X, y = create_seq(scaled, 24)

    model = Sequential()
    model.add(LSTM(32, input_shape=(X.shape[1], 1)))
    model.add(Dense(1))
    model.compile(optimizer="adam", loss="mse")

    model.fit(X, y, epochs=3, batch_size=32, verbose=0)

    last_seq = scaled[-24:].reshape(1, 24, 1)
    pred = model.predict(last_seq)
    pred_kwh = scaler.inverse_transform(pred)[0][0]

    print(f"Predicted Next Night Electricity Usage: {round(pred_kwh, 2)} kWh")
else:
    print("Not enough data after filtering to create sequences for LSTM model.")
    pred_kwh = None

recent = night_data["kwh"].tail(50)

plt.figure(figsize=(8,4))
plt.plot(recent.values)
plt.title("Recent Night Usage Trend")
plt.xlabel("Time Step")
plt.ylabel("kWh")
plt.show()

"""**Reasoning**:
The previous execution produced a `UserWarning` from Keras about passing `input_shape` directly to the `LSTM` layer within a `Sequential` model. To address this, I will add an explicit `Input` layer as the first layer in the `Sequential` model and remove `input_shape` from the `LSTM` layer, as recommended by the warning.


"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Input

df = simulated_df.copy()

df = df / 4

hourly = df.resample("h").sum()

meter = hourly.columns[0]
data = hourly[[meter]].copy()
data.columns = ["kwh"]

data["hour"] = data.index.hour
night_data = data[(data["hour"] >= 19) | (data["hour"] <= 2)].copy()

night_data["day_type"] = np.where(night_data.index.dayofweek < 5, "Weekday", "Weekend")
day_filter = "Weekday"
night_data = night_data[night_data["day_type"] == day_filter]

scaler = MinMaxScaler()
scaled = scaler.fit_transform(night_data[["kwh"]])

def create_seq(data, window=24):
    X, y = [], []
    for i in range(len(data) - window):
        X.append(data[i:i+window])
        y.append(data[i+window])
    return np.array(X), np.array(y)

if len(scaled) >= 24:
    X, y = create_seq(scaled, 24)

    model = Sequential()
    model.add(Input(shape=(X.shape[1], 1)))
    model.add(LSTM(32))
    model.add(Dense(1))
    model.compile(optimizer="adam", loss="mse")

    model.fit(X, y, epochs=3, batch_size=32, verbose=0)

    last_seq = scaled[-24:].reshape(1, 24, 1)
    pred = model.predict(last_seq)
    pred_kwh = scaler.inverse_transform(pred)[0][0]

    print(f"Predicted Next Night Electricity Usage: {round(pred_kwh, 2)} kWh")
else:
    print("Not enough data after filtering to create sequences for LSTM model.")
    pred_kwh = None

recent = night_data["kwh"].tail(50)

plt.figure(figsize=(8,4))
plt.plot(recent.values)
plt.title("Recent Night Usage Trend")
plt.xlabel("Time Step")
plt.ylabel("kWh")
plt.show()