# -*- coding: utf-8 -*-
"""week5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17tAHYGT9pshdEqclw7HcysmAP_Il0TXh

# Welcome to Colab!
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("cleandata.xlsx")

df.head()

df.info()

df['date'] = pd.to_datetime(df['date'])

df['hour'] = df['date'].dt.hour
df['day'] = df['date'].dt.day
df.head()

X = df[['Outdoor Temperature','Occupancy','hour','day']]
y = df['Power Consumption']
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(max_depth=10, random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score

print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))
plt.scatter(y_test, y_pred)

plt.xlabel("Actual Power Consumption")
plt.ylabel("Predicted Power Consumption")
plt.title("Actual vs Predicted Cooling Demand")

plt.show()

importance = model.feature_importances_

import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importance
})

feature_importance

import seaborn as sns

plt.figure(figsize=(6,4))
sns.barplot(x='Importance', y='Feature', data=feature_importance)

plt.title("Feature Importance for Cooling Demand")
plt.show()

heatmap_data = df.pivot_table(
    values='Power Consumption',
    index='hour',
    columns='Occupancy',
    aggfunc='mean'
)

plt.figure(figsize=(8,6))
sns.heatmap(heatmap_data, cmap='coolwarm')

plt.title("Cooling Demand Heatmap")
plt.xlabel("Occupancy")
plt.ylabel("Hour of Day")

plt.show()